version: '3'

services:
  nginx:
    container_name: nginx_prod
    build:
      context: .
      dockerfile: nginx/prod/Dockerfile
    ports:
      - "90:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/prod/prod.conf:/etc/nginx/nginx.conf:ro
      - django-static-prod:/dist/static 
      - front:/dist/
    networks:
      - main

  db:
    container_name: db_prod
    image: mysql:5.7
    networks:
      - main
    volumes:
      - pg-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=KLAUDIA22
      - MYSQL_ROOT_PASSWORD=KLAUDIA22
      - MYSQL_ROOT_HOST=%

  backend:
    container_name: backend_prod
    build: ./backend
    command: /start_prod.sh
    volumes:
      - .:/code
      - django-static-prod:/backend/static
    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - db

networks:
  main:
    driver: bridge

volumes:
  django-static-prod:
  pg-data:
  front:


